version: '3.8'

services:

  keycloak:
    build:
      context: .
      dockerfile: ./opt/keycloak-26.0.5/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - grpc-network

  auth:
    build:
      context: .
      dockerfile: ./internal/auth/Dockerfile
    environment:
      - KEYCLOAK_URL=http://localhost:8080
    ports:
      - "8081:8081"
    networks:
      - grpc-network

  user:
    build:
      context: .
      dockerfile: ./internal/user/main/Dockerfile
    depends_on:
      - auth
    environment:
      - AUTH_SERVICE_URL=http://auth:8081
    ports:
      - "50053:50053"
    networks:
      - grpc-network

  central-grpc-server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    depends_on:
      - auth
      - user
    environment:
      - USER_SERVICE_URL=user:50053
    ports:
      - "50051:50051"
    volumes:
      - certs:/etc/ssl/certs
    networks:
      - grpc-network

  api-gateway:
    build:
      context: .
      dockerfile: ./api/api_gateway/Dockerfile
    depends_on:
      - central-grpc-server
    environment:
      - CENTRAL_GRPC_SERVER_URL=central-grpc-server:50051
    ports:
      - "8000:8000"
    networks:
      - grpc-network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./cert:/etc/prometheus/cert
    ports:
      - "9091:9090"
    networks:
      - grpc-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
networks:
  grpc-network:
    driver: bridge

volumes:
  certs:
