version: '3.8'

services:

  keycloak:
    build:
      context: .
      dockerfile: ./opt/keycloak-26.0.5/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - grpc-network

  auth:
    build:
      context: .
      dockerfile: ./internal/auth/Dockerfile
    environment:
      - KEYCLOAK_URL=http://localhost:8080
    ports:
      - "8081:8081"
    networks:
      - grpc-network

  user:
    build:
      context: .
      dockerfile: ./internal/user/main/Dockerfile
    depends_on:
      - auth
    environment:
      - AUTH_SERVICE_URL=http://auth:8081
    ports:
      - "50053:50053"
    networks:
      - grpc-network

  central-grpc-server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    depends_on:
      - auth
      - user
    environment:
      - USER_SERVICE_URL=user:50053
    ports:
      - "50051:50051"
    volumes:
      - certs:/etc/ssl/certs
    networks:
      - grpc-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - certs:/etc/nginx/cert
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge

volumes:
  certs:  
